### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jaanos** [marinasirk/APPR-2015-16#1]
Poročila ti ne prevede, ker se v njem sklicuješ na spremenljivke iz vzorca. Najbolje bo, če del iz vzorca pobrišeš. Seveda bo potrebno dodati še kak graf iz tvojih podatkov.

Da ti v poročilo ne bo izpisovalo obvestil ob uvozu knjižnic, vse klice ukaza `library` premakni iz `uvoz/uvoz.r` v `lib/libraries.r`. Druga možnost bi bila, da pri bloku, kjer kličeš `uvoz.r`, nastaviš `results='hide'` in `message=FALSE`, da se ta obvestila ne izpisujejo.

**Comment by marinasirk** [comment]
Zanima me zakaj mi ne prevede poročila. Napiše mi naslednje: Error in library(sp): there is no package calles 'sp' Calls: <Anonymous> ... source -> source -> withVisible -> eval -> eval -> library Execution halted

**Comment by jaanos** [comment]
Očitno nimaš nameščene knjižnice `sp`, ki je potreben za risanje zemljevidov in se vključi v `libraries.r`. Tako ga bo treba namestiti (_Tools_ / _Install Packages..._ - mimogrede lahko namestiš še knjižnico `maptools`).

**Comment by marinasirk** [comment]
Aha, to je problem. Hvala.

**Comment by marinasirk** [comment]
Še vedno mi izpisuje knjižnice, čeprav sem jih premaknila v libraries in slika grafa mi skoči vmes besedila. Ali moram nastaviti še kakšen dodaten parameter?

**Comment by jaanos** [comment]
Lahko dodaš še parameter `warning = FALSE`, da ti ne bo izpisovalo opozoril.

Grafi nekoliko skočijo, ker so veliki. Zaenkrat se ni treba ubadati s postavitvijo, boš to kasneje uredila.

**Comment by jaanos** [comment]
Glede na to, da ti zdaj prevede poročilo, bom dodal povezavo nanj. Če boš karkoli spreminjala, mi prosim javi, da jo posodobim.

**Comment by marinasirk** [comment]
Dodala sem še ta parameter in sedaj mi dela. Najlepša hvala.
