### ISSUE TITLE
zemljevid

### ISSUE THREAD

**Issue by marinasirk** [marinasirk/APPR-2015-16#2]
Ko želim pretvoriti zemljevid s funkcijo pretvori.zemljevid, se mi nekje zalomi. Napiše mi to: Regions defined for each Polygons.

**Comment by jaanos** [comment]
S tem ni nič narobe. Če je to vse, kar se izpiše, potem se je funkcija `pretvori.zemljevid` uspešno izvedla.

Seveda nočeš, da bi se ti to sporočilo izpisovalo v poročilu, zato bo treba podati parameter `message = FALSE` pri bloku kode, kjer boš vključila program `vizualizacija.r` (podobno kot imaš že pri `uvoz.r`).

**Comment by marinasirk** [comment]
Aha, v redu. Hvala!
