### ISSUE TITLE
napredna analiza

### ISSUE THREAD

**Issue by marinasirk** [marinasirk/APPR-2015-16#3]
Zanima me, zakaj mi pri napredni analiza (mapa analiza - `analiza.r`) ne dela metoda najmanjših kvadratov `g <- g + geom_smooth(method = "lm", formula = y ~ x + I(x^2))`.

**Comment by jaanos** [comment]
Problem je ta, da je stolpec `LETO` v razpredelnici `razveze3` (pa tudi `razveze2`) faktor, namesto da bi bil številska spremenljivka. Tako bo treba pri uvozu najprej pretvoriti stolpec v števila:

``` R
razveze2$LETO <- as.numeric(razveze2$LETO)
```

Potem lahko sestaviš razpredelnico `razveze3` tako:

``` R
razveze3 <- razveze2 %>% group_by(LETO) %>%
  summarise(STEVILO.RAZVEZ = sum(STEVILO.RAZVEZ)) %>% data.frame()
```

Potem bo graf deloval tako, kot si napisala.

Na podoben način lahko sestaviš še ostale razpredelnice.

**Comment by marinasirk** [comment]
Ok, sedaj pa deluje. Najlepša hvala!
