### ISSUE TITLE
Graf

### ISSUE THREAD

**Issue by marinasirk** [marinasirk/APPR-2015-16#5]
V mapi `uvoz.r` prvi graf prikazuje število razvez po regijah in so na osi x napisana imena regij. Ker so imena zelo dolga, se prekrivajo in se ne vidi dobro. Zanima me, kako naj popravim graf, da bodo recimo imena napisana navpično, ali pa da bo graf obrnjen (zamenjani x in y osi).
In še eno vprašanje imam glede razvrščanja podatkov. Regije naj bi združila v skupine glede na njihovo podobnost, vendar imam podatke zelo razpršene in ne vem kako naj bi to naredila. Imam namreč za vsako regijo podatke o številu razvez glede na trajanje zveze (10 podatkov) in glede na število otrok (5 podatkov).

**Comment by jaanos** [comment]
Besedilo na oseh obrneš tako, da grafu prišteješ npr. `theme(axis.text.x = element_text(angle = 90, vjust = 0.5))`.

Kar se razvrščanja v skupine tiče, bi bilo morda smiselno pridobiti absolutne podatke, da lahko za vsako regijo/kategorijo/leto izračunaš delež razvez. Potem lahko te podatke uporabiš za razvrščanje v skupine (v ta namen podatke spraviš v obliko, kjer je vsaka regija v svoji vrstici in vsak podatek v svojem stolpcu). Ker regij ni veliko, tudi skupin ne sme biti veliko - če se bo seveda sploh pokazala kakšna delitev.

Glede na to, da imaš podatke skozi leta, bi druga možnost bila, da analiziraš trende v deležih razvez pri posamezni kategoriji skozi leta. Tukaj bi sicer šlo bolj za ročno primerjavo in interpretacijo (načeloma bi sicer lahko uporabila parametre dobljenih regresijskih premic kot podatke pri razvrščanju v skupine).

**Comment by marinasirk** [comment]
Hvala za odgovor in pomoč!

**Comment by marinasirk** [comment]
Naredila sem to tabelo v mapi `analiza.r` z imenom razvrscanje, vendar ne vem, kako bi te podatke prikazala na enem grafu. Ne bi želela prikazati podatkov na zemljevidu, saj se mi to ne zdi najbolj smiselno, bi pa rada prikazala na grafu tako, da bi z njega lahko razbrala, katere regije so si podobne med seboj.

**Comment by jaanos** [comment]
Najbolje bo, če narediš razvrščanje na želeno število skupin (seveda ne preveliko), npr.

``` R
razvrscanje.norm <- scale(razvrscanje[-1]) # izpustimo ime regije
rownames(razvrscanje.norm) <- razvrscanje$regija # in ga nastavimo za imena vrstic
k <- kmeans(razvrscanje.norm, 5)
```

Potem si lahko pomagaš z ukazom

``` R
pairs(razvrscanje, col = k$cluster)
```

da izbereš graf, ki je najbolj reprezentativen (lahko se omejiš na določene stolpce, da bo iz dobljene slike kaj videti) in ga potem narišeš na običajen način.

**Comment by marinasirk** [comment]
Sem naredila kar z `geom_point`, ker je dobro razvidno, katere regije gredo skupaj.

Sedaj me pa samo še zanima, če lahko projekt predstavim v HTML obliki, saj je v PDF-u vse pomešano in oznake ne delujejo. Tudi na faksu mi ne dela pravilno v PDF obliki.

**Comment by jaanos** [comment]
Lahko predstaviš v obliki HTML - pravzaprav je to edina možnost, če želiš v poročilo vključiti tudi Shiny.
